services:
  app:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 3000 --reload
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    restart: unless-stopped
